# -*- coding: utf-8 -*-
"""client.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUiEmeCeRCU6EYFUSvWnHabYAoxuu6bt
"""

import socket

HOST = '172.28.0.2' # ip of the server

PORT = 9090

socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.connect((HOST, PORT))

socket.send("Hello World!".encode('utf-8'))
print(socket.recv(1024))
