# -*- coding: utf-8 -*-
"""server.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l5ayQPd6lhzu4nEO6NXHeuRSkE3niAUQ
"""

import socket

host = socket.gethostbyname(socket.gethostname()) # To get IP 

HOST = '172.28.0.2' # IP address of the host, if on same computer then use local host

PORT = 9090
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.bind((HOST, PORT))

server.listen(4) # Number of connection

while True:
  communication_socket, address = server.accept()
  print(f"Connected to {address}")
  message = communication_socket.recv(1024).decode('utf-8')
  print(f"Message from client is: {message}")
  communication_socket.send(f"Got your message! Thank you!".encode('utf-8'))
  communication_socket.close()
  print(f"Connection with {address} ended!")

